---
# tasks file for ec2_instance
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "{{instance_name}}"
    instance_type: "{{type}}"
    security_group: default
    region: "{{region}}"
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    network:
      assign_public_ip: true
    image_id: "{{ami_id}}"
    
