---
- hosts: localhost
  connection: local
  tasks:
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "my_VS_Key"
      instance_type: t2.micro
      security_group: default
      region: us-east-2
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
    
    loop:
      - { image: "ami-085f9c64a9b75eed5", name: "manage-node-1" }
      - { image: "ami-085f9c64a9b75eed5", name: "manage-node-2" }
      - { image: "ami-09efc42336106d2f2", name: "manage-node-3" }
